language: java

dist: trusty

jdk: oraclejdk8

cache:
  directories:
    - $HOME/.mvn/


addons:
  sonarcloud:
    organization: "lucaskatayama-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_KEY # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn clean test
  - sonar-scanner
